{% set name = "flake8-annotations" %}
{% set version = "2.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-annotations-{{ version }}.tar.gz
  sha256: 52e53c05b0c06cac1c2dec192ea2c36e85081238add3bd99421d56f574b9479b

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - poetry
    - python
    - pip
    - pyopenssl >=20  # [py36 and win]
  run:
    - flake8 >=3.7, <4.0
    - python
    - typed-ast >=1.4,<2.0  # [py<38]

test:
  imports:
    - flake8_annotations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sco1/flake8-annotations
  summary: Flake8 Type Annotation Checks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
    - muyajil
