{% set name = "flake8-annotations" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-annotations-{{ version }}.tar.gz
  sha256: a2765c6043098aab0a3f519b871b33586c7fba7037686404b920cf8100cc1cdc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.8
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - attrs >=21.4.0,<22.0.0
    - flake8 >=3.7

test:
  imports:
    - flake8_annotations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sco1/flake8-annotations
  summary: Flake8 Type Annotation Checks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
    - muyajil
