{% set name = "flake8-annotations" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8_annotations-{{ version }}.tar.gz
  sha256: 6c98968ccc6bdc0581d363bf147a87df2f01d0d078264b2da805799d911cf5fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.2
    - pip
  run:
    - python >=3.8.1,<4.0.0
    - attrs >=21.4
    - flake8 >=5.0

test:
  imports:
    - flake8_annotations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sco1/flake8-annotations
  summary: Flake8 Type Annotation Checks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
    - muyajil
