{% set name = "flake8-annotations" %}
{% set version = "2.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-annotations-{{ version }}.tar.gz
  sha256: 40a4d504cdf64126ea0bdca39edab1608bc6d515e96569b7e7c3c59c84f66c36

build:
  number: 0
  skip: true  # [py>=40 or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - flake8 >=3.7,<3.9
    - python
    - typed-ast >=1.4,<2.0  # [py<38]

test:
  imports:
    - flake8_annotations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sco1/flake8-annotations
  summary: Flake8 Type Annotation Checks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - muyajil
